const userTickets = [
  {
    ticket_id: 1,
    user_id: 1,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: "Sammy",
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resoved: null,
  },
  {
    ticket_id: 2,
    user_id: 2,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: "Sammy",
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resoved: null,
  },
  {
    ticket_id: 3,
    user_id: 3,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: "Sammy",
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resoved: null,
  },
  {
    ticket_id: 4,
    user_id: 4,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: "Sammy",
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resoved: null,
  },
  {
    ticket_id: 5,
    user_id: 5,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: "Sammy",
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resoved: null,
  },
  {
    ticket_id: 6,
    user_id: 6,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: "Sammy",
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resoved: null,
  },
  {
    ticket_id: 7,
    user_id: 7,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: "Sammy",
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resoved: null,
  },
  {
    ticket_id: 8,
    user_id: 8,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: "Sammy",
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resoved: null,
  },
  {
    ticket_id: 9,
    user_id: 9,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: "Sammy",
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resoved: null,
  },
  {
    ticket_id: 10,
    user_id: 10,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: "Sammy",
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resoved: null,
  },
  {
    ticket_id: 1,
    user_id: 1,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: "Sammy",
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resoved: null,
  },
  {
    ticket_id: 2,
    user_id: 2,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: "Sammy",
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resoved: null,
  },
  {
    ticket_id: 3,
    user_id: 3,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: "Sammy",
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resoved: null,
  },
  {
    ticket_id: 4,
    user_id: 4,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: "Sammy",
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resoved: null,
  },
  {
    ticket_id: 5,
    user_id: 5,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: "Sammy",
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resoved: null,
  },
  {
    ticket_id: 6,
    user_id: 6,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: "Sammy",
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resoved: null,
  },
  {
    ticket_id: 7,
    user_id: 7,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: "Sammy",
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resoved: null,
  },
  {
    ticket_id: 8,
    user_id: 8,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: "Sammy",
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resoved: null,
  },
  
];


export default userTickets