const userTickets = [
  {
    ticket_id: 1,
    user_id: 1,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional All modem wall plugs in build 5500 are not functional",
    assigned: false,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: true,
  },
  {
    ticket_id: 2,
    user_id: 2,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: false,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: null,
  },
  {
    ticket_id: 3,
    user_id: 3,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: false,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: null,
  },
  {
    ticket_id: 4,
    user_id: 4,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: true,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: null,
  },
  {
    ticket_id: 5,
    user_id: 5,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: true,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: true,
  },
  {
    ticket_id: 6,
    user_id: 6,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: true,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: null,
  },
  {
    ticket_id: 6,
    user_id: 6,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: true,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: null,
  },
  {
    ticket_id: 1,
    user_id: 1,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: false,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: true,
  },
  {
    ticket_id: 2,
    user_id: 2,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: false,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: null,
  },
  {
    ticket_id: 3,
    user_id: 3,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: false,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: null,
  },
  {
    ticket_id: 4,
    user_id: 4,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: true,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: null,
  },
  {
    ticket_id: 5,
    user_id: 5,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: true,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: true,
  },
  {
    ticket_id: 6,
    user_id: 6,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: true,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: null,
  },
  {
    ticket_id: 6,
    user_id: 6,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: true,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: null,
  },
  {
    ticket_id: 1,
    user_id: 1,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: false,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: true,
  },
  {
    ticket_id: 2,
    user_id: 2,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: false,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: null,
  },
  {
    ticket_id: 3,
    user_id: 3,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: false,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: null,
  },
  {
    ticket_id: 4,
    user_id: 4,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: true,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: null,
  },
  {
    ticket_id: 5,
    user_id: 5,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: true,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: true,
  },
  {
    ticket_id: 6,
    user_id: 6,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: true,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: null,
  },
  {
    ticket_id: 6,
    user_id: 6,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: true,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: null,
  },
  {
    ticket_id: 1,
    user_id: 1,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: false,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: true,
  },
  {
    ticket_id: 2,
    user_id: 2,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: false,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: null,
  },
  {
    ticket_id: 3,
    user_id: 3,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: false,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: null,
  },
  {
    ticket_id: 4,
    user_id: 4,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: true,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: null,
  },
  {
    ticket_id: 5,
    user_id: 5,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: true,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: true,
  },
  {
    ticket_id: 6,
    user_id: 6,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: true,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: null,
  },
  {
    ticket_id: 6,
    user_id: 6,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: true,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: null,
  },
  {
    ticket_id: 1,
    user_id: 1,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: false,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: true,
  },
  {
    ticket_id: 2,
    user_id: 2,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: false,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: null,
  },
  {
    ticket_id: 3,
    user_id: 3,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: false,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: null,
  },
  {
    ticket_id: 4,
    user_id: 4,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: true,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: null,
  },
  {
    ticket_id: 5,
    user_id: 5,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: true,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: true,
  },
  {
    ticket_id: 6,
    user_id: 6,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: true,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: null,
  },
  {
    ticket_id: 6,
    user_id: 6,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: true,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: null,
  },
  {
    ticket_id: 1,
    user_id: 1,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: false,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: true,
  },
  {
    ticket_id: 2,
    user_id: 2,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: false,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: null,
  },
  {
    ticket_id: 3,
    user_id: 3,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: false,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: null,
  },
  {
    ticket_id: 4,
    user_id: 4,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: true,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: null,
  },
  {
    ticket_id: 5,
    user_id: 5,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: true,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: true,
  },
  {
    ticket_id: 6,
    user_id: 6,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: true,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: null,
  },
  {
    ticket_id: 6,
    user_id: 6,
    category: "Infrastructure",
    description: "All modem wall plugs in build 5500 are not functional",
    assigned: true,
    priority: "urgent",
    eta: "2 days",
    email: "sammy@gmail.com",
    status: "not started",
    campus_id: 4,
    create_data: "4/25/1995",
    resolved: null,
  },
];

export default userTickets;
